// A list of all actions in the system.
import { createTypes } from 'reduxsauce'

export default createTypes(`
  LOGIN_ATTEMPT
  LOGIN_SUCCESS
  LOGIN_FAILURE

  LOGOUT

  STARTUP

  JOBS_RECEIVE
  JOBS_RECEIVE_FAILURE
  POSTED_JOBS_RECEIVE_FAILURE
  POSTED_JOBS_RECEIVE
  POSTED_JOBS_DETAILS_SET
  POSTED_JOBS_DETAILS_SET_FAILURE
  APPLIED_JOBS_RECEIVE
  APPLIED_JOBS_RECEIVE_FAILURE

  SELECT_JOB_FOR_DETAILS
`)
